version: 2.1

jobs:
  build:
    docker:
      - image: circleci/16.20.2
    working_directory: "~/repp"
    steps:
      - checkout
      - run:
          name: show current branch
          command: echom ${CURRENT_BRANCH}
      - restore_cache:
          key:
            - app-{{ checksum $"package.json" }}
            - app-
      - run:
          name: install yarn
          command: npm install --global yarn
      - run:
          name: insatll dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key:
            - app-{{ checksum $"package.json" }}

  # deploy-to-aws-s3:
  #   docker:
  #      - image: circleci/16.20.2
  #   working_directory: "/"
  #   steps:
  #    - checkout 
  #    - run: 
  #       name: show current branch
  #       command: echom ${CURRENT_BRANCH}
  #    - run:
  #       name: "install aws"
  #       command : | 
  #          sudo apt-get -y -qq update 
  #          sudo apt-get install -y awscli
  #          sudo apt-get install -y python-pip python-dev build-essential
  #   - run:   
  #       name:  install yarn
  #       command: npm install --global yarn
  #   - run : 
  #       name:  build project
  #       command: | 
  #          yarn install 
  #          yarn run build
  #          cd build
  #          zip ../build.zip -r * .[^.]*
  #          echo build successfull
  #   - run : 
  #     name: doploy to aws s3
  #     command: |
  #        if[ "${CURRENT_BRANCH}" === "master" ]
  #        then

